/* SELECT CUST_NUM
FROM dbo.CUSTOMERS
WHERE CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS); */

/* SELECT O.ORDER_NUM, O.ORDER_DATE, O.CUST, O.REP, O.MFR, O.PRODUCT, O.QTY, O.AMOUNT
FROM dbo.ORDERS AS O
INNER JOIN dbo.CUSTOMERS AS C 
    ON O.CUST = C.CUST_NUM
WHERE C.CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS); */

/* SELECT O.CUST, O.ORDER_NUM, O.ORDER_DATE, O.REP, O.MFR, O.PRODUCT, O.QTY, O.AMOUNT
FROM dbo.ORDERS AS O
INNER JOIN dbo.CUSTOMERS AS C 
    ON O.CUST = C.CUST_NUM
WHERE C.CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS)
  AND O.ORDER_DATE = (
        SELECT MAX(O2.ORDER_DATE)
        FROM dbo.ORDERS AS O2
        INNER JOIN dbo.CUSTOMERS AS C2 
            ON O2.CUST = C2.CUST_NUM
        WHERE C2.CREDIT_LIMIT = (SELECT MAX(CREDIT_LIMIT) FROM dbo.CUSTOMERS)
  ); */

