/* SELECT 
    [CITY], 
    [MGR]
FROM 
    [dbo].[OFFICES]
WHERE 
    [REGION] = 'Eastern' AND 
    [TARGET] <= 350000.00; */

/* SELECT *
FROM [dbo].[ORDERS]
WHERE 
    YEAR([ORDER_DATE]) NOT BETWEEN 2008 AND 2008
    AND (
        [PRODUCT] LIKE '_A%' 
        OR [PRODUCT] LIKE '%0%'
    ); */ 


/* SELECT 
    [MFR], 
    COUNT(DISTINCT [ORDER_NUM]) AS [UNIQUE_ORDERS], 
    SUM([AMOUNT]) AS [TOTAL_AMOUNT]
FROM 
    [dbo].[ORDERS]
WHERE 
    YEAR([ORDER_DATE]) NOT BETWEEN 2008 AND 2008
    AND (
        [PRODUCT] LIKE '_A%' 
        OR [PRODUCT] LIKE '%0%'
    )
GROUP BY 
    [MFR]
ORDER BY 
    [TOTAL_AMOUNT] ASC; */

/* SELECT 
    MFR AS Manufacturer, 
    COUNT(DISTINCT ORDER_NUM) AS UniqueOrders, 
    SUM(AMOUNT) AS TotalAmount
FROM [dbo].[ORDERS]
WHERE 
    ORDER_DATE NOT BETWEEN '2008-01-01' AND '2008-12-31'
    AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY MFR
ORDER BY TotalAmount ASC; */

/* SELECT TOP 1 WITH TIES 
    MFR AS Manufacturer, 
    SUM(AMOUNT) AS TotalAmount
FROM [dbo].[ORDERS]
WHERE 
    ORDER_DATE NOT BETWEEN '2008-01-01' AND '2008-12-31'
    AND (PRODUCT LIKE '_A%' OR PRODUCT LIKE '%0%')
GROUP BY MFR
ORDER BY SUM(AMOUNT) DESC; */

/* SELECT TOP 1 WITH TIES 
    REP_OFFICE AS OfficeID, 
    COUNT(*) AS EmployeeCount
FROM [dbo].[SALESREPS]
WHERE 
    TITLE = 'Sales Rep'
    AND AGE IN (29, 45, 48)
GROUP BY REP_OFFICE
ORDER BY EmployeeCount DESC; */

/* SELECT TOP 1 WITH TIES
    MFR_ID AS ManufacturerID,
    PRODUCT_ID AS ProductID,
    DESCRIPTION AS ProductDescription,
    LEN(DESCRIPTION) AS DescriptionLength
FROM [dbo].[PRODUCTS]
ORDER BY LEN(DESCRIPTION) DESC; */

/* SELECT DISTINCT
    CONCAT_WS(' ', RTRIM(UPPER(MFR_ID)), RTRIM(UPPER(PRODUCT_ID)), RTRIM(UPPER(DESCRIPTION))) AS ConcatenatedString,
    LEN(CONCAT_WS(' ', RTRIM(UPPER(MFR_ID)), RTRIM(UPPER(PRODUCT_ID)), RTRIM(UPPER(DESCRIPTION)))) AS ConcatenatedLength
FROM [dbo].[PRODUCTS]
WHERE PRODUCT_ID NOT LIKE '%[^0-9]%'
ORDER BY ConcatenatedLength DESC; */

/* SELECT 
    CUST_NUM AS CustomerID,
    CONCAT(SUBSTRING(COMPANY, 1, 2), REPLICATE('*', LEN(COMPANY) - 4), SUBSTRING(COMPANY, LEN(COMPANY) - 1, 2)) AS MaskedCompanyName,
    CREDIT_LIMIT AS CreditLimit
FROM [dbo].[CUSTOMERS]
WHERE CREDIT_LIMIT = (SELECT MIN(CREDIT_LIMIT) FROM [dbo].[CUSTOMERS])
ORDER BY CustomerID; */

