/* SELECT DISTINCT O.MFR
FROM dbo.CUSTOMERS C
INNER JOIN dbo.ORDERS O ON C.CUST_NUM = O.CUST
WHERE C.COMPANY LIKE '%CORP%' 
  AND O.ORDER_DATE >= '2008-01-01' 
  AND O.ORDER_DATE < '2009-01-01'; */

/* SELECT 
    C.CUST_NUM, 
    MONTH(O.ORDER_DATE) AS ORDER_MONTH,
    COUNT(DISTINCT O.ORDER_NUM) AS UNIQUE_ORDERS
FROM 
    dbo.CUSTOMERS AS C
LEFT JOIN 
    dbo.ORDERS AS O 
    ON C.CUST_NUM = O.CUST
    AND YEAR(O.ORDER_DATE) = 2008
WHERE 
    C.COMPANY LIKE '%CORP%'
GROUP BY 
    C.CUST_NUM, MONTH(O.ORDER_DATE)
ORDER BY 
    UNIQUE_ORDERS DESC; */

/* SELECT 
    C.CUST_NUM,
    UPPER(C.COMPANY) AS COMPANY_NAME,
    P.DESCRIPTION
FROM 
    dbo.CUSTOMERS AS C
LEFT JOIN 
    dbo.ORDERS AS O 
    ON C.CUST_NUM = O.CUST 
    AND YEAR(O.ORDER_DATE) = 2008
LEFT JOIN 
    dbo.PRODUCTS AS P 
    ON O.MFR = P.MFR_ID 
    AND O.PRODUCT = P.PRODUCT_ID
WHERE 
    C.COMPANY LIKE '%CORP%'
GROUP BY 
    C.CUST_NUM, UPPER(C.COMPANY), P.DESCRIPTION
ORDER BY 
    C.CUST_NUM; */
